### ISSUE TITLE
Egghead setup not working

### ISSUE THREAD

**Issue by martijnsenden** [kentcdodds/es6-todomvc#17]
Hi,

Just forked your repo and tried to get it to work. I added your repo as an upstream remote. I then did a `git fetch -all`. Then I did `npm run setup:egghead`. This results in a message saying Exit status 1. I'm on node v6.2.2 and npm 3.9.5. Any thoughts on what could be wrong? This is the output I have in `npm-debug.log`:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'setup:egghead' ]
2 info using npm@3.9.5
3 info using node@v6.2.2
4 verbose run-script [ 'presetup:egghead', 'setup:egghead', 'postsetup:egghead' ]
5 info lifecycle @~presetup:egghead: @
6 silly lifecycle @~presetup:egghead: no script for presetup:egghead, continuing
7 info lifecycle @~setup:egghead: @
8 verbose lifecycle @~setup:egghead: unsafe-perm in lifecycle true
9 verbose lifecycle @~setup:egghead: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/awesome/Sites/training/egg-webpack-production/node_modules/.bin:/usr/local/bin:/usr/local/bin:/usr/local/opt/php56/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/mysql/bin/
10 verbose lifecycle @~setup:egghead: CWD: /Users/awesome/Sites/training/egg-webpack-production
11 silly lifecycle @~setup:egghead: Args: [ '-c',
11 silly lifecycle   'git checkout prelesson/polyfill-promises && npm install && mkdir dist && npm run validate' ]
12 silly lifecycle @~setup:egghead: Returned: code: 1  signal: null
13 info lifecycle @~setup:egghead: Failed to exec setup:egghead script
14 verbose stack Error: @ setup:egghead: `git checkout prelesson/polyfill-promises && npm install && mkdir dist && npm run validate`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:245:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid @
16 verbose cwd /Users/awesome/Sites/training/egg-webpack-production
17 error Darwin 15.6.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "setup:egghead"
19 error node v6.2.2
20 error npm  v3.9.5
21 error code ELIFECYCLE
22 error @ setup:egghead: `git checkout prelesson/polyfill-promises && npm install && mkdir dist && npm run validate`
22 error Exit status 1
23 error Failed at the @ setup:egghead script 'git checkout prelesson/polyfill-promises && npm install && mkdir dist && npm run validate'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the  package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     git checkout prelesson/polyfill-promises && npm install && mkdir dist && npm run validate
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by kentcdodds** [comment]
Give it another shot now. I made some updates.

**Comment by kentcdodds** [comment]
Please re-open if you still have issues.
