### ISSUE TITLE
npm run setup:fem fails....Need help!

### ISSUE THREAD

**Issue by vinothkumarshanker** [kentcdodds/es6-todomvc#28]
When I run npm run setup:fem.... seems lint fails....

My npm and node versions:
npm -v = 3.8.6
node -v = v6.0.0

```
23:40:29-yc03648~/workshop/webpack/es6-todomvc (master)$ npm run setup:fem

> @ setup:fem /Users/yc03648/workshop/webpack/es6-todomvc
> git checkout FEM/07.1-deploy-surge && npm install && npm run validate && rimraf dist coverage && git checkout FEM/00-original-project

Branch FEM/07.1-deploy-surge set up to track remote branch FEM/07.1-deploy-surge from origin.
Switched to a new branch 'FEM/07.1-deploy-surge'
npm WARN karma-webpack@1.7.0 requires a peer of webpack@^1.4.0 but none was installed.

> @ validate /Users/yc03648/workshop/webpack/es6-todomvc
> npm-run-all --parallel lint build test


> @ lint /Users/yc03648/workshop/webpack/es6-todomvc
> eslint .

▀ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟

> @ test /Users/yc03648/workshop/webpack/es6-todomvc
> karma start
▀ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟

> @ prebuild /Users/yc03648/workshop/webpack/es6-todomvc
> rimraf dist

> @ build /Users/yc03648/workshop/webpack/es6-todomvc
> webpack --env.prod -p

  build [==                  ] 10%
/Users/yc03648/workshop/webpack/es6-todomvc/src/app.js
  1:8   error  Unable to resolve path to module 'todomvc-app-css/index.css'  import/no-unresolved
  2:8   error  Unable to resolve path to module './app.css'                  import/no-unresolved
  4:19  error  Unable to resolve path to module './helpers'                  import/no-unresolved
  5:26  error  Unable to resolve path to module './todo'                     import/no-unresolved
  6:25  error  Unable to resolve path to module './graph'                    import/no-unresolved

/Users/yc03648/workshop/webpack/es6-todomvc/src/bootstrap.js
  2:41  error  Unable to resolve path to module 'offline-plugin/runtime'  import/no-unresolved
  3:22  error  Unable to resolve path to module './app'                   import/no-unresolved
  4:19  error  Unable to resolve path to module './helpers'               import/no-unresolved

/Users/yc03648/workshop/webpack/es6-todomvc/src/controller.test.js
  1:24  error  Unable to resolve path to module './controller'  import/no-unresolved

/Users/yc03648/workshop/webpack/es6-todomvc/src/graph/index.js
  1:34  error  Unable to resolve path to module '../todo'  import/no-unresolved

/Users/yc03648/workshop/webpack/es6-todomvc/src/graph/render.js
  1:19  error  Unable to resolve path to module 'react'      import/no-unresolved
  2:22  error  Unable to resolve path to module 'react-dom'  import/no-unresolved
  3:24  error  Unable to resolve path to module 'rd3'        import/no-unresolved
  4:21  error  Unable to resolve path to module 'lodash'     import/no-unresolved

/Users/yc03648/workshop/webpack/es6-todomvc/src/store.js
  1:22  error  Unable to resolve path to module './helpers'  import/no-unresolved

/Users/yc03648/workshop/webpack/es6-todomvc/src/todo.js
  1:18  error  Unable to resolve path to module './view'        import/no-unresolved
  2:24  error  Unable to resolve path to module './controller'  import/no-unresolved
  3:19  error  Unable to resolve path to module './model'       import/no-unresolved
  4:19  error  Unable to resolve path to module './store'       import/no-unresolved
  5:22  error  Unable to resolve path to module './template'    import/no-unresolved
  6:22  error  Unable to resolve path to module './helpers'     import/no-unresolved

/Users/yc03648/workshop/webpack/es6-todomvc/src/view.js
  2:48  error  Unable to resolve path to module './helpers'  import/no-unresolved

✖ 22 problems (22 errors, 0 warnings)


npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/yc03648/.nvm/versions/node/v6.0.0/bin/node" "/Users/yc03648/.nvm/versions/node/v6.0.0/bin/npm" "run-script" "lint"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! @ lint: `eslint .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ lint script 'eslint .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     eslint .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/yc03648/workshop/webpack/es6-todomvc/npm-debug.log

> @ postbuild /Users/yc03648/workshop/webpack/es6-todomvc
> cpy favicon.ico dist

ERROR: "lint" exited with 1.

npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/yc03648/.nvm/versions/node/v6.0.0/bin/node" "/Users/yc03648/.nvm/versions/node/v6.0.0/bin/npm" "run" "validate"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! @ validate: `npm-run-all --parallel lint build test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ validate script 'npm-run-all --parallel lint build test'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm-run-all --parallel lint build test
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/yc03648/workshop/webpack/es6-todomvc/npm-debug.log

npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/yc03648/.nvm/versions/node/v6.0.0/bin/node" "/Users/yc03648/.nvm/versions/node/v6.0.0/bin/npm" "run" "setup:fem"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! @ setup:fem: `git checkout FEM/07.1-deploy-surge && npm install && npm run validate && rimraf dist coverage && git checkout FEM/00-original-project`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ setup:fem script 'git checkout FEM/07.1-deploy-surge && npm install && npm run validate && rimraf dist coverage && git checkout FEM/00-original-project'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     git checkout FEM/07.1-deploy-surge && npm install && npm run validate && rimraf dist coverage && git checkout FEM/00-original-project
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/yc03648/workshop/webpack/es6-todomvc/npm-debug.log
```

**Comment by kentcdodds** [comment]
Hmmm.... It appears there may be an issue with `eslint-plugin-import`. Could you try this again in a day or two (maybe the bug will be fixed by then). Or you might dig a little deeper.

On the bright side, the linting stuff isn't super important, so you should be able to continue by running `git checkout FEM/00-original-project` and start from there...

**Comment by egrobler** [comment]
I get this error (not pasting everything, just the part where the syntax error starts:

> @ build /work/other/frontendmasters.com/webpack/es6-todomvc
> webpack --env.prod -p

06 01 2017 13:06:06.586:ERROR [config]: Invalid config file!
  SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/work/other/frontendmasters.com/webpack/es6-todomvc/karma.conf.js:3:23)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.parseConfig (/work/other/frontendmasters.com/webpack/es6-todomvc/node_modules/karma/lib/config.js:307:22)
    at new Server (/work/other/frontendmasters.com/webpack/es6-todomvc/node_modules/karma/lib/server.js:56:20)


Is this a karma config file error or webpack config file?

**Comment by kentcdodds** [comment]
This is most likely because you're using the wrong version of node. Make sure you're on version 6

**Comment by egrobler** [comment]
I hate to say this, but yes I was still on v.4.6.1... Somehow seeing the "6" in there made me think it was on version 6... silly me.

Upgraded node and npm to latest and greatest and your steps are working fine now. Thanks!

**Comment by rharing** [comment]
just cloned the repo and tried npm run validate after the npm install:
node -v: 8.7.0 
npm -v: 5.6.0
errors:
9 verbose lifecycle @~validate: CWD: /home/ronald/projects/tryout/ikwilnunaardefilm/src/main/webapp/js/es6-todomvc
 14 10 silly lifecycle @~validate: Args: [ '-c', 'npm-run-all --parallel lint build test' ]
 15 11 silly lifecycle @~validate: Returned: code: 1  signal: null
 16 12 info lifecycle @~validate: Failed to exec validate script
 17 13 verbose stack Error: @ validate: `npm-run-all --parallel lint build test`
 18 13 verbose stack Exit status 1
 19 13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
 20 13 verbose stack     at emitTwo (events.js:125:13)
 21 13 verbose stack     at EventEmitter.emit (events.js:213:7)
 22 13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
 23 13 verbose stack     at emitTwo (events.js:125:13)
 24 13 verbose stack     at ChildProcess.emit (events.js:213:7)
 25 13 verbose stack     at maybeClose (internal/child_process.js:927:16)
 26 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
 27 14 verbose pkgid @
 28 15 verbose cwd /home/ronald/projects/tryout/ikwilnunaardefilm/src/main/webapp/js/es6-todomvc
                                                                                                                          15,1          50%
