### ISSUE TITLE
Error thrown on branch change

### ISSUE THREAD

**Issue by TheSETJ** [kentcdodds/es6-todomvc#38]
Hello.

OS: Windows 10 Version 1709.
Node: 8.10.0
NPM: 5.6.0

Every time I use `git checkout -f <branch-name>` command, the branch will change but I get this error:

```
Already on 'FEM/00-original-project'
Your branch is up-to-date with 'origin/FEM/00-original-project'.
module.js:549
    throw err;
    ^

Error: Cannot find module 'E:\cygdrive\e\dev\vscode\webpack-deep-dive\es6-todomvc\.git\hooks\post-checkout'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

I also followed setup instruction for windows 10 and still I get the error.

**Comment by kentcdodds** [comment]
Delete your `.git/hooks` directory and it should work fine.
